{% set version = "2.9.0" %}

package:
  name: h5py
  version: {{ version }}

source:
   url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
   sha256: 49d593c07a3a4cb87ed421f502e34368b98282a4ac6d4388379aab80b11c7924

build:
  number: 2001

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - hdf5
    - python
    - pip
    - numpy
    - cython
    - pkgconfig
    - six
    - mpich # [not win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - six
    - mpich # [not win]
    - hdf5
    - pyreadline  # [win]

test:
  imports:
    - h5py


about:
  home: https://github.com/h5py/h5py.git
  license: BSD
  license_file: licenses/license.txt
  summary: Python wrappers for hdf5 library
