{% set version = "2.7.1" %}

package:
  name: h5py
  version: {{ version }}

source:
   url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python 3.6.*
    - setuptools
    - numpy 1.13.*
    - cython
    - pkgconfig
    - six
    - mpich # [not win]
    - hdf5-parallel
  run:
    - python
    - numpy
    - cython
    - pkgconfig
    - six
    - mpich # [not win]
    - hdf5-parallel

test:
  imports:
    - h5py


about:
  home: https://github.com/h5py/h5py.git
  license: BSD
  license_file: licenses/license.txt
  summary: Python wrappers for hdf5 library
