{% set version = "2.8.0" %}

package:
  name: h5py
  version: {{ version }}

source:
   url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
   sha256: eae41382be28b7264824450ce343dd625f972bedaaa3b0cced284986aabcbaee

build:
  number: 1005

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - hdf5
    - python 3.7
    - pip
    - numpy
    - cython
    - pkgconfig
    - six
    - mpich # [not win]

  run:
    - python 3.7
    - numpy
    - six
    - mpich # [not win]
    - hdf5
    - pyreadline  # [win]

test:
  imports:
    - h5py


about:
  home: https://github.com/h5py/h5py.git
  license: BSD
  license_file: licenses/license.txt
  summary: Python wrappers for hdf5 library
