parameters:
  name: ''
  vmImage: ''
  allowFailure: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    # - script: |
    #     buildscripts\\install_conda.bat "%UserProfile%\\Miniconda3"
    #   displayName: 'Install conda'

    - script: |
        IF "%USE_NUMBA_MASTER%" == "False" (
            "C:\\Miniconda\\python.exe" buildscripts\\build.py --build-mode=package --python=%PYTHON_VER% --numpy=%NUMPY_VER% --skip-smoke-tests --conda-prefix="C:\\Miniconda"
            ) ELSE (
            "C:\\Miniconda\\python.exe" buildscripts\\build.py --build-mode=package --python=%PYTHON_VER% --numpy=%NUMPY_VER% --use-numba-master --conda-prefix="C:\\Miniconda")
      displayName: 'Build conda and wheel packages'
      continueOnError: ${{ parameters.allowFailure }}

    - script: |
        IF "%USE_NUMBA_MASTER%" == "False" (
            "C:\\Miniconda\\python.exe" buildscripts\\test.py --test-mode=conda --python=%PYTHON_VER% --numpy=%NUMPY_VER% --skip-smoke-tests --conda-prefix="C:\\Miniconda"
            ) ELSE (
            "C:\\Miniconda\\python.exe" buildscripts\\test.py --test-mode=conda --python=%PYTHON_VER% --numpy=%NUMPY_VER% --use-numba-master --conda-prefix="C:\\Miniconda")
      displayName: 'Test conda package'
      continueOnError: ${{ parameters.allowFailure }}
