parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: |
        buildscripts\\install_conda.bat "%UserProfile%\\Miniconda3"
      displayName: 'Install conda'

    - script: |
        "%UserProfile%\\Miniconda3\\python.exe" buildscripts\\build.py --build-mode=package --python=%PYTHON_VER% --numpy=%NUMPY_VER% --conda-prefix="%UserProfile%\\Miniconda3"
      displayName: 'Build conda and wheel packages'

    - script: |
        "%UserProfile%\\Miniconda3\\python.exe" buildscripts\\test.py --test-mode=conda --python=%PYTHON_VER% --numpy=%NUMPY_VER% --conda-prefix="%UserProfile%\\Miniconda3"
      displayName: 'Test conda package'
