{% set version = "1.10.4" %}
{% set maj_min_ver = ".".join(version.split(".")[:2]) %}

package:
  name: hdf5
  version: {{ version }}

source:
  fn: hdf5-{{ version }}.tar.gz
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-{{ maj_min_ver }}/hdf5-{{ version }}/src/hdf5-{{ version }}.tar.gz
  sha256: 8f60dc4dd6ab5fcd23c750d1dc5bca3d0453bdce5c8cdaf0a4a61a9d1122adb2

build:
  number: 1002

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.2.2              # [win]
    - python >=3.6
    - mpich                      # [not win]
    - libtool                    # [unix]
    - ninja                      # [win]
  host:
    - zlib
  run:
    - zlib
    - mpich # [not win]


about:
  home: https://www.hdfgroup.org/
  license: BSD
  license_file: COPYING
  summary: Parallel HDF5 library
