package:
  name: hpat
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python 3.6.*
    - setuptools
    - numba 0.38.*
    - numpy 1.14.*
    - pandas 0.23
    - mpich # [not win]
    - pyarrow 0.9.*
    - boost-cpp
    - hdf5
    - h5py
    - opencv 3.3.1
    - hpat-parquet-reader # [not win]

  run:
    - python 3.6.*
    - numpy 1.14.*
    - pandas 0.23
    - mpich # [not win]
    - pyarrow 0.9.*
    - boost-cpp
    - numba 0.38.*
    - hdf5
    - h5py
    - hpat-parquet-reader # [not win]

test:
  imports:
    - hpat


about:
  home: https://github.com/IntelLabs/hpat
  license: BSD
  license_file: LICENSE.md
  summary: A compiler-based big data framework in Python
