{% set version = "0.29.2" %}
{% set buildnumber = 1 %}

package:
  name: hpat
  version: {{version}}

source:
   path: ../..

build:
  number: {{buildnumber}}
  script_env:
    - HPAT_CONFIG_MPI
    - HPAT_NUM_PES
    - HPAT_RUN_COVERAGE

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - numba ==0.45
    - numpy
    - pandas >=0.23
    - pyarrow >=0.9
    - arrow-cpp
    - boost
    - hdf5
    - h5py
    - mpich # [not win]
    - impi_rt # [win]
    - impi-devel # [win]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=0.23
    - pyarrow >=0.9
    - arrow-cpp
    - boost
    - numba ==0.45
    - mpich # [not win]
    - impi_rt # [win]

test:
  requires:
    - h5py
    - scipy
    - coveralls
  imports:
    - hpat


about:
  home: https://github.com/IntelPython/hpat
  license: BSD
  license_file: LICENSE.md
  summary: A compiler-based big data framework in Python
