{% set NUMBA_VERSION = "==0.49.1" %}
{% set PANDAS_VERSION = "==0.25.3" %}
{% set PYARROW_VERSION = "==0.17.0" %}

package:
  name: sdc
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
    - SDC_CONFIG_PIPELINE_SDC

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - wheel
    - python

  host:
    - python
    - setuptools
    - numba   {{ NUMBA_VERSION }}
    - numpy
    - pandas  {{ PANDAS_VERSION }}
    - pyarrow {{ PYARROW_VERSION }}
    - wheel

  run:
    - python
    - numpy
    - pandas  {{ PANDAS_VERSION }}
    - pyarrow {{ PYARROW_VERSION }}
    - numba   {{ NUMBA_VERSION }}
    - setuptools

test:
  imports:
    - sdc

outputs:
  - type: conda
    name: sdc
  - type: wheel
    name: sdc
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python
        - wheel
        - setuptools
        - numba   {{ NUMBA_VERSION }}
        - numpy
        - pandas  {{ PANDAS_VERSION }}
        - pyarrow {{ PYARROW_VERSION }}

about:
  home: https://github.com/IntelPython/sdc
  license: BSD
  license_file: LICENSE.md
  summary: A compiler-based big data framework in Python
