{% set NUMBA_VERSION = "==0.46" %}
{% set PANDAS_VERSION = "<1.0.0a0" %}
{% set PYARROW_VERSION = "==0.15.1" %}
{% set ARROW_CPP_VERSION = "==0.15.1" %}

package:
  name: sdc
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script_env:
    - SDC_CONFIG_PIPELINE_SDC

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - wheel
    - python

  host:
    - python
    - setuptools
    - numba {{ NUMBA_VERSION }}
    - numpy
    - pandas {{ PANDAS_VERSION }}
    - pyarrow {{ PYARROW_VERSION }}
    - arrow-cpp {{ ARROW_CPP_VERSION }}
    - boost
    - conda-package-handling ==1.3.11 # [win]
    - wheel

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas {{ PANDAS_VERSION }}
    - pyarrow {{ PYARROW_VERSION }}
    - arrow-cpp {{ ARROW_CPP_VERSION }}
    - boost
    - numba {{ NUMBA_VERSION }}
    - conda-package-handling ==1.3.11 # [win]

test:
  requires:
    - scipy
  imports:
    - sdc

outputs:
  - type: conda
    name: sdc
  - type: wheel
    name: sdc
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python
        - wheel
        - setuptools
        - numba {{ NUMBA_VERSION }}
        - numpy
        - pandas {{ PANDAS_VERSION }}
        - pyarrow {{ PYARROW_VERSION }}
        - arrow-cpp {{ PYARROW_VERSION }}
        - boost
        - conda-package-handling ==1.3.11 # [win]

about:
  home: https://github.com/IntelPython/sdc
  license: BSD
  license_file: LICENSE.md
  summary: A compiler-based big data framework in Python
