apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: data-pd
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-data
spec:
  storageClassName: ""
  volumeName: pv-data
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10G
