package:
  name: hpat-parquet-reader
  version: "0.1.1"

source:
   path: ../../parquet_reader

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.2
    - python 3.6.*
    - pyarrow ==0.14.1
    - arrow-cpp ==0.14.1
  run:
    - pyarrow ==0.14.1
    - arrow-cpp ==0.14.1


about:
  home: https://github.com/IntelLabs/hpat
  license: BSD
  summary: Parquet reader for HPAT
