parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool: 
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH

    - script: conda create -q -y -n %CONDA_ENV% python=%PYTHON_VER% conda-build conda-verify vc vs2015_runtime vs2015_win-64
      displayName: Create Anaconda environment

    - script: |
        SET %HPAT_WHEELS_DIR% = "%CD%\hpat-wheels"
        echo "HPAT_WHEELS_DIR"
        echo %HPAT_WHEELS_DIR%
        call activate %CONDA_ENV%
        conda build --python %PYTHON_VER% --numpy=%NUMPY_VER% --override-channels -c numba -c https://metachannel.conda-forge.org/conda-forge/python,setuptools,numpy,pandas,pyarrow,arrow-cpp,boost,hdf5,h5py,conda-package-handling,wheel,coveralls,pip -c defaults -c intel buildscripts/hpat-conda-recipe/
      displayName: conda build