parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 60
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 11
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - script: |
        echo "Installing Miniconda"
        buildscripts/setup_conda.sh
        export PATH=$HOME/miniconda3/bin:$PATH
      displayName: 'Setup Miniconda'
    - script: |
        export PATH=$HOME/miniconda3/bin:$PATH
        buildscripts/build.sh
      displayName: 'Build'